### ISSUE TITLE
Hasher doesnt't work

### ISSUE THREAD

**Issue by dolorosus** [simu/passwordhasherplus#2]
I followed the instructions, put my PW in a PW field. 
Hitting the '*' in the bubble revealed my PW, but hitting '#' doesn't change the PW.
What's wrong?

**Comment by simu** [comment]
Can you give me the following information:

* Browser version
* Website which shows this behavior
* Plugin version
* Whether you use compatibility mode or not

Thanks

**Comment by dolorosus** [comment]
Am 04.06.17 um 15:54 schrub Simon Gerber:

> Can you give me the following information:
>
>   * Browser version
53.0.3 (32-Bit)


>   * Website which shows this behavior
https://checkdeinpasswort.de/

>   * Plugin version
2.3.10

>   * Whether you use compatibility mode or not
>
Compatibility mode wasn't  used

BTW: Every time I open up the settings page, all settings are reset to default values. I don't think this behavior is intentioned

**Comment by simu** [comment]
Thanks for the report.

The hash button works, but the Javascript code on that site does not recheck your password when the field contents are replaced by the plugin without a key being pressed. Using the key combination Ctrl+'#', the site picked up on the hashed password when I was testing just now.

I'm looking into this, but I haven't figured out a reliable way of triggering a site's onchange event without retriggering the hashing with the current plugin architecture.

Re settings page: have you clicked the save button after changing settings?

**Comment by dolorosus** [comment]
Am 04.06.17 um 20:08 schrub Simon Gerber:
> Thanks for the report.
>
> The hash button works, but the Javascript code on that site does not
> recheck your password when the field contents are replaced by the plugin
> without a key being pressed. Using the key combination Ctrl+'#', the
> site picked up on the hashed password when I was testing just now.
>
> I'm looking into this, but I haven't figured out a reliable way of
> triggering a site's onchange event without retriggering the hashing with
> the current plugin architecture.

Ok, this seem to be a issue caused by the architecture of this addon. Having a dependency to the target site and it's code may cause unpredictable results... From my point of view not the best decision.

>
> Re settings page: have you clicked the save button after changing settings?
>

Shure, more than once...

Best wishes
Dolorosus

**Comment by simu** [comment]
Re settings: might be that you were running into issues because the settings could be deleted by clearing browser history, cf. #4. That should be fixed in the latest version on AMO,  v2.4.0.

Also, because I'm trying to move away from having users enter their master password in the actual password field, cf. #3, we should not have to worry about websites doing funny stuff to the password field anymore.
