### ISSUE TITLE
Class .hidden conflicts with some sites

### ISSUE THREAD

**Issue by LiPeK** [simu/passwordhasherplus#24]
I frequently visit two sites that use their own .hidden class (that does not define display:none inside) in their body element.

When this add-on is enabled, those pages disappear:
- https://player.pl/ (click menu button or search button)
- articles on wykop.pl, like this:
  http://www.wykop.pl/ramka/5155703/spanie-mniej-niz-6-godzin-i-choroby-serca-udar-to-smiertelna-kombinacja/
 (list of such articles: https://www.wykop.pl/szukaj/url%3Awykop.pl/? )

**Comment by simu** [comment]
Thanks for the report, I had seen this issue myself, but hadn't made the connection. I'll properly prefix the extension classes, to avoid this in the next release.

**Comment by simu** [comment]
This has been addressed in PR #26 and the fix will be part of the next release.
